### ISSUE TITLE
Can't install the gem theme

### ISSUE THREAD

**Issue by brando90** [pages-themes/hacker#44] opened 2019-09-11 03:32 UTC
```
(base) brandomiranda~/awesome-static-site $ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    jekyll-compose was resolved to 0.11.0, which depends on
      jekyll (>= 3.7, < 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by brando90** [comment] 2019-09-11 03:33
```
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.0.0"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
#gem "minima", "~> 2.5"
#gem "jekyll-athena"
#Optionally, if you'd like to preview your site on your computer, add the following to your site's Gemfile:
#https://github.com/pages-themes/hacker
gem "github-pages", group: :jekyll_plugins


# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

gem 'jekyll-compose', group: [:jekyll_plugins]

```

**Comment by LuisEnMarroquin** [comment] 2019-11-05 18:50
You need `jekyll (~> 3.3)`

**Comment by Merovex** [comment] 2019-11-27 15:19
I have the same problem. I forced `jekyll-theme-hacker` to be 0.1.1 and received a different error.

```
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-theme-hacker (~> 0.1.1) was resolved to 0.1.1, which depends on
      jekyll (~> 3.5)
```

**Comment by Merovex** [comment] 2020-01-26 20:53
I ended up abandoning use of this gem because of this.

**Comment by clumsymass64** [comment] 2020-03-01 00:51
Hi, @brando90 I was encountering the same issue so I downgraded my version of jekyll to 3.7.3 by changing the following line in Gemfile:
`gem "jekyll", "~> 4.0.0"`
to
`gem "jekyll", "~> 3.7.3"`

and then in terminal, i ran the command:
`bundle install`

It fixed the issue for me permanently. I think this jekyll theme doesn't support jekyll 4.0.0 yet. Of course, the next step was 
`bundle exec jekyll serve`

and voila.

**Comment by xirsoi** [comment] 2020-03-19 18:06
I can confirm that the solution above works, but that doesn't mean this gem shouldn't be fixed!
@benbalter please consider a new release for the gem so people don't need to do a hack to use the theme.

**Comment by AwlsomeAlex** [comment] 2020-05-23 22:05
@clumsymass64 Works for me too.

**Comment by tanant** [comment] 2020-06-09 02:27
@benbalter / @parkr What would you need for a PR or other things to wrap what we have up here and do a 0.1.2 (or 0.2.0) release, is it just the `gemspec`? The last release of this was 0.1.1 from 8364d7a about 2 years ago and in the meantime looks like there's been a few PRs merged, notably one relaxing the version restriction for Jekyll 4.x.

Main reason for wanting to get this updated is for those people running through the Jekyll quickstart. I'm guessing what's happening is that they do a local build and when exploring themes go to GitHub Pages and notice that there's a dozen supported themes which they'll try, but they'll not realize that GitHub pages only on Jekyll 3.8.7, and are probably not going to figure out that they need to switch the gemfile to using the github pages bundle.

**Comment by parkr** [comment] 2020-08-08 17:53
0.1.2 is released: https://github.com/pages-themes/hacker/releases/tag/v0.1.2

**Closed by parkr** 2020-08-08 17:53 UTC
Labels: wontfix
